artifact_location: /Users/rabinpoudel/Documents/code_code_Code/dl/transformer_from_scratch/none/597266778588425367
creation_time: 1766675702922
experiment_id: '597266778588425367'
last_update_time: 1766675702922
lifecycle_stage: active
name: gpt_train
